// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blloljzzrzxesnlgevfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsbG9sanp6cnp4ZXNubGdldmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzc2MDgsImV4cCI6MjA3MjkxMzYwOH0.x0b54ACFG61sDWAb_003qIXmeSXLzDpH-vY9bgiqp_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});